baseurl: 'https://patcon.github.io/awesome-polis'
relativeurls: true
languageCode: en
pluralizelisttitles: false
removePathAccents: true
canonifyURLs: true
title: Awesome Polis

disableKinds:
  - taxonomyTerm

params:
  Description: >-
    Useful resources for using Polis and building things on top of it
  image: /images/polis-banner.jpeg